### ISSUE TITLE
Wishlist: specify custom source

### ISSUE THREAD

**Issue by sigio** [picatz/doh#2]
it would be nice to be able to specify a custom source on the commandline, for example when testing your own DoH gateway/server, instead of having to use the predefined sources.

**Comment by picatz** [comment]
I really like that idea! 👍

I'll look into adding a custom/user-supplied source.

**Comment by sigio** [comment]
That's quick .... In the meantime I found another doh client that already had this capability, but it's nice to have choices ;)
